name: Planviser
options:
  bundleIdPrefix: com.planviser
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"
  AppAuth:
    url: https://github.com/openid/AppAuth-iOS.git
    from: "1.7.0"
  MSAL:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc.git
    from: "1.5.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: "2.6.0"

targets:
  Planviser:
    type: application
    platform: macOS
    sources:
      - Planviser
    settings:
      base:
        INFOPLIST_FILE: Planviser/Info.plist
        CODE_SIGN_ENTITLEMENTS: Planviser/Planviser.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.planviser.app
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 96AL947RQ2
    dependencies:
      - package: KeychainAccess
      - package: AppAuth
      - package: MSAL
      - package: Sparkle
        product: Sparkle
